# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-19 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0002_auto_20171116_0500'),
    ]

    operations = [
        migrations.CreateModel(
            name='cafeinfo',
            fields=[
                ('num', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('x', models.CharField(max_length=30)),
                ('y', models.CharField(max_length=30)),
                ('roadAddr', models.CharField(max_length=50)),
            ],
        ),
    ]
