# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-20 00:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0003_cafeinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cafeinfo',
            old_name='name',
            new_name='cafename',
        ),
    ]
